# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: NatilusCode
tagline: the mobile code editor
email: your-email@domain.com
description: >
  NautilusCode the mobile code editor. With full git integration it lets
  you integrate your iPad into your development workflow.
baseurl: ""
url: "http://www.nautiluscode.ch" # the base hostname & protocol for your site
timezone: Europe/Zurich
github_username: alehed

# Build settings
markdown: kramdown

# Custom Collections
collections:
  - features

# Frontmatter defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
